/**
 * For more information on testing with the Authorize.Net Sandbox see:
 * https://developer.authorize.net/hello_world/testing_guide.html
 */
public class AuthorizeDotNetSandbox {

    public final static String AMERICAN_EXPRESS = '370000000000002';
    
    public final static String DISCOVER = '6011000000000012';
    
    public final static String VISA = '4111111111111111';
    
    public final static String MASTERCARD = '2223000010309711';
}